[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "atk",
  "at-spi2-atk",
  "cups",
  "drm",
  "dbus",
  "expat",
  "libxcb",
  "libxkbcommon",
  "mesa",
  "nspr",
  "pango",
  "cairo",
  "gtk3"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]
